spring.application.name=SpringBootBatchProcessing
spring.datasource.url = jdbc:mysql://localhost:3306/springBatchProcessing
spring.datasource.username = root
spring.datasource.password = root

spring.batch.jdbc.initialize-schema=always

spring.batch.job.enabled=false
server.port=8080